### ISSUE TITLE
does not compile

### ISSUE THREAD

**Issue by Shilovms** [makerbase-mks/MKS-SGen#11]
The firmware is not compiled. Visual studio with platformio can't compile, throws errors.

**Comment by mks-viva** [comment]
You need tell me，what the firmware you use？Or provide it to me

**Comment by Shilovms** [comment]
I took the Marlin-bugfix-2.0.x firmware from the MKS-SGen-master file from here

**Comment by mks-viva** [comment]
Oh! MKS SGEN path marlin firmware is not the latest version, you can download the letest version marlin test it.
