### ISSUE TITLE
TMC connection error, Marlin 2.0.x

### ISSUE THREAD

**Issue by imaluschi** [makerbase-mks/MKS-SGen#3]
Please add Documentation for installing drivers and Marlin FW.
In my case: SGEN, Marlin bugfix-2.0.x and TMC 2008
The LCD-Display shows: TMC CONNECTION ERROR
I don't know why, the drivers are placed correctly (EN-,DIR-, and GND-Pin). What's wrong and how to resolve?

**Comment by Fighter777** [comment]
+1 same for me

**Comment by makerbase-mks** [comment]
About MKS SGEN use TMC2208/2209 uart mode
1. #define DRIVE_TYPE  TMC2208
2. Connect to uart pin 
![image](https://user-images.githubusercontent.com/12979070/82281632-6e379e80-99c4-11ea-819b-9942274bae30.png)
